JEST=./node_modules/.bin/jest
$JEST \
  --coverage --no-cache --runInBand \
  --projects \
    ./packages/command \
    ./packages/command-plus \
    ./packages/dep-merge \
    ./packages/dep-merge-cli \
    ./packages/dep-pointer \
    ./packages/dep-pointer-cli \
    ./packages/gitpkg.traverse-up \
    ./packages/gitpkg.upsert \
    ./packages/help \
    ./packages/help.filter-until \
    ./packages/help.parse-argv \
    ./packages/help.set-entire \
    ./packages/help.string-argv \
    ./packages/here \
    ./packages/journey \
    ./packages/journey.coerce-to-array \
    ./packages/journey.coerce-to-plain-object \
    ./packages/journey.fn-free \
    ./packages/journey.fn-reduce \
    ./packages/journey.is-promise \
    ./packages/journey.pass-thru \
    ./packages/lerna.paths \
    ./packages/lerna.utils \
    ./packages/monorepo-babel-cli \
    ./packages/monorepo-dep-lint-cli \
    ./packages/pkg \
    ./packages/pkg-cli \
    ./packages/pkg-plugin-babel-6-to-node-4 \
    ./packages/pkg-plugin-babel-7-to-node-4 \
    ./packages/pkg-plugin-cobalt \
    ./packages/pkg-plugin-jest \
    ./packages/pkg-plugin-name-dir \
    ./packages/pkg-plugin-name-scope \
    ./packages/pkg-plugin-prop \
    ./packages/pkg-plugin-sort \
    ./packages/pkg-plugin-standard \
    ./packages/pkg.file-exists \
    ./packages/pkg.fs \
    ./packages/pkg.is-local-module \
    ./packages/pkg.json-parse \
    ./packages/pkg.pretty-json \
    ./packages/pkg.prop-overwrite \
    ./packages/pkg.read-json \
    ./packages/pkg.throw-error \
    ./packages/pkgprop \
    ./packages/pkgprop-cli \
    ./packages/reggi-cli \
    ./packages/replace-cli \
    ./packages/requireable \
    ./packages/requireable-cli \
    ./packages/results-cli \
    ./packages/shebang-check \
    ./packages/shebang-check-cli \
    ./packages/subrepo \
    ./packages/subrepo-cli \
