#!/usr/bin/env bash
USAGE="--cleanCoverage (clean all html files of timestamp)"
function cleanCoverage {
  a="generated by <a href=\"https:\/\/istanbul.js.org\/\" target=\"_blank\">istanbul<\/a> .* (Eastern Daylight Time)"
  b="generated by <a href=\"https:\/\/istanbul.js.org\/\" target=\"_blank\">istanbul<\/a>"
  case "$OSTYPE" in
    linux*)   find ./coverage -type f -name '*.html' -print0 | xargs -0 sed -e "s/$a/$b/g" ;;
    darwin*)  find ./coverage -type f -name '*.html' -print0 | xargs -0 sed -i '' -e "s/$a/$b/g" ;; 
  esac
}
